"""empty message

Revision ID: 564b41d83cc4
Revises: c7f6e268ddbf
Create Date: 2024-03-27 15:32:28.804076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '564b41d83cc4'
down_revision = 'c7f6e268ddbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('car_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['car_id'], ['cars.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('post_model')
    # ### end Alembic commands ###
