"""empty message

Revision ID: c7f6e268ddbf
Revises: 
Create Date: 2024-03-27 15:12:06.260868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7f6e268ddbf'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carmake', sa.String(length=50), nullable=True),
    sa.Column('dealer', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=75), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cars')
    # ### end Alembic commands ###
